CREATE DATABASE CUAHANGSACH_ONLINE
USE CUAHANGSACH_ONLINE


CREATE TABLE SANPHAM (
	MaSP VARCHAR(10) PRIMARY KEY ,
	MaDanhMuc VARCHAR(10) NOT NULL,
	Ma_NCC VARCHAR(10),
	TenSP NVARCHAR(255) NOT NULL,
	GiaSP NUMERIC(16,2),
	TacGia NVARCHAR(255),
	Bia NVARCHAR(20),
	TonKho INT,
	TGTao DATETIME DEFAULT GETDATE(),
	TGCapNhat DATETIME DEFAULT GETDATE()
);


CREATE TABLE NHACUNGCAP(
	Ma_NCC VARCHAR(10) PRIMARY KEY,
	Ten_NCC NVARCHAR(255) NOT NULL,
	SDT CHAR(20)
);

CREATE TABLE DANHMUC (
	MaDanhMuc VARCHAR(10) PRIMARY KEY,
	TenDanhmuc NVARCHAR(255) NOT NULL,
); 

CREATE TABLE DONHANG (
	MaDH VARCHAR(10) PRIMARY KEY,
	MaKH VARCHAR(10) NOT NULL,
	MaGiamGia_DH VARCHAR(10),
	MaDiaChi VARCHAR(10) ,
	NgayDat DATETIME NOT NULL DEFAULT GETDATE(),
	NgayGiao DATETIME,
	TongDonGia NUMERIC(16,2),
	GiamGia_DonHang NUMERIC(16,2), 
	PhiVanChuyen NUMERIC(16,2), 
	ThanhTien NUMERIC(16,2),
	TrangThai NVARCHAR(30) NOT NULL DEFAULT N'chờ xử lý',
	TGTao DATETIME DEFAULT GETDATE(),
	TGCapNhat DATETIME DEFAULT GETDATE()
);

CREATE TABLE DIACHINHAN(
	MaDiaChi VARCHAR(10) PRIMARY KEY,
	MaKH VARCHAR(10) NOT NULL,
	HoTen_NguoiNhan NVARCHAR(255),
	SoDienThoai CHAR(20),
	DiaChi NVARCHAR(1000) NOT NULL,
	QuanHuyen NVARCHAR(1000) NOT NULL,
	ThanhPho NVARCHAR(1000) NOT NULL,
	GhiChu NVARCHAR(1000)

);
CREATE TABLE CHITIET_DONHANG(
	MaDH VARCHAR(10)NOT NULL,
	MaSP VARCHAR(10) NOT NULL,
	MaGiamGia_DM VARCHAR(10),
	SoLuong NUMERIC(16,2) NOT NULL,
	DonGia NUMERIC(16,2) ,
	LuongGiam NUMERIC(16,2)
);


CREATE TABLE CHITIET_THANHTOAN(
	MaThanhToan VARCHAR(10) NOT NULL ,
	MaDH VARCHAR(10) NOT NULL,
	NgayThanhToan DATETIME,
	TrangThai_TT NVARCHAR(30) NOT NULL  DEFAULT N'xử lý',
	TGTao DATETIME DEFAULT GETDATE(),
	TGCapNhat DATETIME DEFAULT GETDATE()
);

CREATE TABLE KHACHHANG(
	MaKH VARCHAR(10) PRIMARY KEY,
	TenNguoiDung VARCHAR(255) NOT NULL ,
	MatKhau VARCHAR(255),
	TenKH NVARCHAR(255) NOT NULL,
	NgaySinh DATETIME,
	GioiTinh NVARCHAR(3),
	SoDienThoai CHAR(20) NOT NULL,
	Email VARCHAR(50),
);

CREATE TABLE DANHGIA(
	MaDH VARCHAR(10) NOT NULL,
	MaSP VARCHAR(10) NOT NULL,
	NoiDung NVARCHAR(1000),
	SoDiem TINYINT NOT NULL,
	NgayDanhGia DATETIME,
	TGTao DATETIME DEFAULT GETDATE(),
	TGCapNhat DATETIME DEFAULT GETDATE()
);
CREATE TABLE GIAMGIA_DANHMUC(
	MaGiamGia_DM VARCHAR(10) PRIMARY KEY,
	GiaTri NUMERIC(16,2),
	LoaiGiaTri VARCHAR(20),
	NoiDung NVARCHAR(255),
	SoLuongMa INT,
	GiaTri_ToiThieu NUMERIC(16,2),
	GiamToiDa NUMERIC(16,2),
	TGBatDau DATETIME,
	TGKetThuc DATETIME,
	TrangThai TINYINT DEFAULT 1,
	TGTao DATETIME DEFAULT GETDATE(),
	TGCapNhat DATETIME DEFAULT GETDATE()

);
CREATE TABLE GIAMGIA_DONHANG(
	MaGiamGia_DH VARCHAR(10) PRIMARY KEY,
	GiaTri NUMERIC(16,2),
	LoaiGiaTri VARCHAR(20),
	NoiDung NVARCHAR(255),
	SoLuongMa INT,
	GiaTri_ToiThieu NUMERIC(16,2),
	GiamToiDa NUMERIC(16,2),
	TGBatDau DATETIME,
	TGKetThuc DATETIME,
	TrangThai TINYINT DEFAULT 1,
	TGTao DATETIME DEFAULT GETDATE(),
	TGCapNhat DATETIME DEFAULT GETDATE()

);

CREATE TABLE GIOHANG(
	MaKH VARCHAR(10) NOT  NULL ,
	MaSanPham VARCHAR(10) NOT NULL,
	TenSP NVARCHAR(255) NOT NULL,
	SoLuong INT,
	TGTao DATETIME DEFAULT GETDATE(),
	TGCapNhat DATETIME DEFAULT GETDATE()
);
CREATE TABLE DANHMUC_GIAM
(
	MaGiamGia_DM VARCHAR(10)NOT NULL,
	MaDanhMuc VARCHAR(10) NOT NULL,

);
CREATE TABLE THANHTOAN(
	MaThanhToan VARCHAR(10) PRIMARY KEY,
	LoaiThanhToan NVARCHAR(20) NOT NULL,
);
CREATE TABLE DANGNHAP(
	MaDangNhap VARCHAR(10) PRIMARY KEY,
	TenDangNhap VARCHAR(255) NOT NULL,
	MatKhau VARCHAR(255)NOT NULL,
	TrangThai NVARCHAR(30) NOT NULL
);



ALTER TABLE GIOHANG
ADD CONSTRAINT PK_GIOHANG PRIMARY KEY (MAKH,MASANPHAM);
ALTER TABLE DANHMUC_GIAM
ADD CONSTRAINT PK_DANHMUC_GIAM PRIMARY KEY (MaDanhMuc,MaGiamGia_DM);
ALTER TABLE CHITIET_THANHTOAN 
ADD CONSTRAINT PK_CHITIET_THANHTOAN PRIMARY KEY (MADH,MATHANHTOAN);
ALTER TABLE CHITIET_DONHANG 
ADD CONSTRAINT PK_CHITIET_DONHANG PRIMARY KEY (MADH,MASP);
ALTER TABLE DANHGIA
ADD CONSTRAINT PK_DANHGIA_MADH_MASP PRIMARY KEY (MADH,MASP);


ALTER TABLE KHACHHANG
ADD CONSTRAINT UN_KHACHHANG_TENNGUOIDUNG UNIQUE(TENNGUOIDUNG);



ALTER TABLE SANPHAM
ADD CONSTRAINT FK_SANPHAM_DM FOREIGN KEY (MADANHMUC) REFERENCES DANHMUC(MADANHMUC);
ALTER TABLE SANPHAM
ADD CONSTRAINT FK_SANPHAM_NCC FOREIGN KEY (MA_NCC) REFERENCES NHACUNGCAP(MA_NCC);
ALTER TABLE CHITIET_DONHANG
ADD CONSTRAINT FK_CHITIET_DONHANG_CTDH FOREIGN KEY (MADH) REFERENCES DONHANG(MADH) ON DELETE CASCADE;
ALTER TABLE  CHITIET_THANHTOAN
ADD CONSTRAINT FK_CHITIET_THANHTOAN_TT FOREIGN KEY (MaThanhToan) REFERENCES THANHTOAN(MaThanhToan);
ALTER TABLE CHITIET_THANHTOAN
ADD CONSTRAINT FK_CHITIET_THANHTOAN_DH FOREIGN KEY (MADH) REFERENCES DONHANG(MADH);
ALTER TABLE DONHANG
ADD CONSTRAINT FK_DONHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH);
ALTER TABLE CHITIET_DONHANG
ADD CONSTRAINT FK_CHITIETDONHANG_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP);
ALTER TABLE  DANHGIA
ADD CONSTRAINT FK_DANHGIA_SANPHAM FOREIGN KEY (MaSP) REFERENCES SANPHAM(MASP);
ALTER TABLE DANHGIA 
ADD CONSTRAINT FK_DANHGIA_DONHANG FOREIGN KEY (MADH) REFERENCES DONHANG (MADH);
ALTER TABLE CHITIET_DONHANG
ADD CONSTRAINT FK_CHITIET_DONHANG_GG FOREIGN KEY (Magiamgia_DM) REFERENCES GIAMGIA_DANHMUC (Magiamgia_DM);
ALTER TABLE GIOHANG
ADD CONSTRAINT FK_GIOHANG_SP FOREIGN KEY (MaSanPham) REFERENCES SANPHAM (MaSP);
ALTER TABLE GIOHANG
ADD CONSTRAINT FK_GIOHANG_KH FOREIGN KEY (MaKH) REFERENCES KHACHHANG (MaKH);
ALTER TABLE DIACHINHAN 
ADD CONSTRAINT FK_DIACHINHAN_KH FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH);
ALTER TABLE DONHANG
ADD CONSTRAINT FK_DONHANG_DIACHINHAN FOREIGN KEY (MADIACHI) REFERENCES DIACHINHAN (MADIACHI);
ALTER TABLE DANHMUC_GIAM
ADD CONSTRAINT FK_DANHMUC_GIAM_GIAMGIA FOREIGN KEY (MAGIAMGIA_DM) REFERENCES GIAMGIA_DANHMUC(MAGIAMGIA_DM);
ALTER TABLE DANHMUC_GIAM
ADD CONSTRAINT FK_DANHMUC_GIAM_DANHMUC FOREIGN KEY (MADANHMUC) REFERENCES DANHMUC(MADANHMUC);
ALTER TABLE DONHANG
ADD CONSTRAINT FK_DONHANG_GIAMGIA_DONHANG FOREIGN KEY (MAGIAMGIA_DH) REFERENCES GIAMGIA_DONHANG(MAGIAMGIA_DH);
